### ISSUE TITLE
When I change a build.yaml and the server is out of sync it throws an error

### ISSUE THREAD

**Issue by joshuacook** [databricks-edu/build-tooling#88]

**Comment by joshuacook** [comment]
I should be able to `course download` even the server is missing files that are in the build.yaml? open to that I shouldn't be able but currently annoyed

**Comment by joshuacook** [comment]
```
"09-Delta-Lab.py" -> /Users/joshuacook/repos/enablement/modules/delta/06-Delta-Lab.py
Traceback (most recent call last):
  File "/usr/local/bin/course", line 11, in <module>
    load_entry_point('course==2.5.0', 'console_scripts', 'course')()
  File "/usr/local/lib/python3.7/site-packages/course-2.5.0-py3.7.egg/course/__init__.py", line 1159, in main
  File "/usr/local/lib/python3.7/site-packages/course-2.5.0-py3.7.egg/course/__init__.py", line 680, in download
  File "/usr/local/lib/python3.7/site-packages/bdc-1.34.0-py3.7.egg/bdc/__init__.py", line 2887, in bdc_download
  File "/usr/local/lib/python3.7/site-packages/bdc-1.34.0-py3.7.egg/bdc/__init__.py", line 2600, in download_notebooks
  File "/usr/local/lib/python3.7/site-packages/bdc-1.34.0-py3.7.egg/bdc/__init__.py", line 2567, in do_download
  File "/usr/local/lib/python3.7/site-packages/bdc-1.34.0-py3.7.egg/bdc/bdcutil.py", line 322, in move
  File "/usr/local/lib/python3.7/site-packages/bdc-1.34.0-py3.7.egg/bdc/bdcutil.py", line 1603, in _do_copy
OSError: "09-Delta-Lab.py" does not exist.
```

**Comment by bmc** [comment]
The tool doesn't handle that, because it's not the "usual" workflow. But I'm not averse to adding a check that prints a warning, rather than aborting. Meanwhile, the workaround, obviously, is to create an empty notebook before downloading.

**Comment by joshuacook** [comment]
I have a few workarounds. Today it was ten renamed notebooks and I wasn't sure if there was anything of value on the server so I just said yolo ran `course cleansource upload` without doing a download first. 

I suppose I could have done cmd+z to the previous state of the build, download, then shift-cmd-z and upload.

I think a warning would be my preferred behavior. FWIW I hit this a lot because of the nature of the work we are doing (a lot of moving existing content around to match a particular request).
